#include"stdafx.h"
#include"Block.h"
#include"SentenceParser.h"

voidBlock::returnSpace()
{
	while(!temp_space_stack_.empty())
	{
		block_space_stack_.push(temp_space_stack_.top());
		temp_space_stack_.pop();
	}
}

Object*Block::searchObject(stringvar_name)
{
	//####
	//####
	returnnullptr;
	//####
	//####
	Object*object=nullptr;
	while(!block_space_stack_.empty())
	{
		object=block_space_stack_.top()->var_table_[var_name];
		if(object!=nullptr)
		{
			returnSpace();
			returnobject;
		}
		temp_space_stack_.push(block_space_stack_.top());
		block_space_stack_.pop();
	}
	returnSpace();
	returnnullptr;
}

voidBlock::print_all()
{
	for(autoit=sentence_vector_->begin();it!=sentence_vector_->end();++it)
	{
		SentenceParser*sp=newSentenceParser((*it));
		sp->print_test_second();
		deletesp;
	}
}

voidBlock::print_all_old()
{
	for(autoit=sentence_vector_->begin();it!=sentence_vector_->end();++it)
	{
		SentenceParser*sp=newSentenceParser((*it));
		sp->print_test_first();
		deletesp;
	}
}
