#include"stdafx.h"
#include"ParseFuncSwitcher.h"

voidFuncSwitcher(Block*cur,Node*node)
{
	switch(node->getNodeType())
	{
		/*
		caseNodeType::TERMINATE:
			Object*value=node->value_;
			if(value->getType()==ObjectType::Operator)
			{
				node->parent_->nodeType_=
			}
		break;
		default:
			cout<<node->getNodeType()<<endl;
		break;
		*/
	default:;
	}
}
